version: '2'
services:
  api:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=TRUE
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
