version: '3'
services:
  api:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: "TRUE"
    depends_on:
      - db
      - backend
  api_test:
    build:
      context: ./
      dockerfile: test/Dockerfile
    volumes:
      - .:/opt/app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      PYTHONUNBUFFERED: "TRUE"
    depends_on:
      - api
    command: ["test"]
  worker:
    build:
      context: .
      dockerfile: src/tasks/Dockerfile
    entrypoint: ["celery"]
    environment:
      DB_HOST: db
      DB_PORT: 5432
    command: ["-A", "celery_app", "worker", "--loglevel=INFO"]
    depends_on:
      - db
      - backend
  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - 5430:5432
  backend:
    image: redis
    ports:
      - 7000:6379
